Repository canonical/feast-operators, pull requests merged in 2025-06, with the labels that each got.

#34 (ci)chore: enable cache for charm builds
  .github/workflows/ci.yaml
Labels: Libraries: Out of sync

#35 fix: typo in feature store secret template
  charms/feast-integrator/src/templates/feature_store_secret.yaml.j2
Labels: Libraries: Out of sync

#31 fix: `fest-ui` ingress integration
  charms/feast-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py
  charms/feast-ui/metadata.yaml
  charms/feast-ui/poetry.lock
  charms/feast-ui/pyproject.toml
  charms/feast-ui/src/charm.py
  charms/feast-ui/src/components/pebble_component.py
  charms/feast-ui/tests/integration/test_charm.py
  charms/feast-ui/tests/unit/test_charm.py
Labels: Libraries: Out of sync

#39 fix: rename feast integrator env variable name
  charms/feast-integrator/src/templates/feature_store_poddefault.yaml.j2
Labels: Libraries: OK, Libraries: Out of sync

#42 feat: add docs index page
  docs/.custom_wordlist.txt
  docs/index.rst
Labels: Libraries: Out of sync

#43 feat: use refacotred feast-ui rock
  charms/feast-ui/metadata.yaml
Labels: Libraries: Out of sync

#44 feat: update how-to guide on how to use scipy image
  docs/how-to/use_charmed_feast.rst
Labels: Libraries: OK
